-- CreateTable
CREATE TABLE "ficha_cooperado_form" (
    "id" TEXT NOT NULL,
    "cooperative_id" TEXT NOT NULL,
    "venc_cooperados" TEXT,
    "matricula" TEXT,
    "unique_id_bubble" TEXT,
    "slug" TEXT,
    "nome_cooperado" TEXT,
    "cpf_cooperado" TEXT,
    "rg" TEXT,
    "nis_pis" TEXT,
    "ctps_serie" TEXT,
    "nacionalidade" TEXT,
    "naturalidade" TEXT,
    "nascimento" TIMESTAMP(3),
    "sexo" TEXT,
    "estado_civil" TEXT,
    "escolaridade" TEXT,
    "nome_pai" TEXT,
    "nome_mae" TEXT,
    "nome_conjuge" TEXT,
    "cpf_conjuge" TEXT,
    "celular_cooperado" TEXT,
    "telefone_residencial" TEXT,
    "email_cooperado" TEXT,
    "celular_indicador" TEXT,
    "email_indicador" TEXT,
    "nome_indicacao" TEXT,
    "email_gestor" TEXT,
    "endereco" TEXT,
    "bairro" TEXT,
    "complemento" TEXT,
    "cep" TEXT,
    "cidade" TEXT,
    "estado" TEXT,
    "empresa_trabalho" TEXT,
    "cargo_pretendido" TEXT,
    "cargo_contratado" TEXT,
    "salario" TEXT,
    "data_admissao" TIMESTAMP(3),
    "data_cadastro" TIMESTAMP(3),
    "ativ_coop_dropa" TEXT,
    "ativ_coop_dropb" TEXT,
    "atividades_cooperados" TEXT,
    "outras_ativd_profissionais" TEXT,
    "banco" TEXT,
    "agencia" TEXT,
    "conta_corrente" TEXT,
    "pix" TEXT,
    "capital_social" TEXT,
    "carteira_registro" TEXT,
    "atestados_tecnicos" TEXT,
    "curriculo_profissional" TEXT,
    "descricao_sucinta" TEXT,
    "valor_acumulado" TEXT,
    "valor_atual" TEXT,
    "valor_integralizado" TEXT,
    "valor_var" TEXT,
    "parcelas" TEXT,
    "em_aberto" TEXT,
    "local_cadastro" TEXT,
    "imagem_cooperado" TEXT,
    "creation_date" TIMESTAMP(3),
    "modified_date" TIMESTAMP(3),
    "creator" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "ficha_cooperado_form_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "ficha_cooperado_form_unique_id_bubble_key" ON "ficha_cooperado_form"("unique_id_bubble");

-- CreateIndex
CREATE INDEX "ficha_cooperado_form_cooperative_id_cpf_cooperado_idx" ON "ficha_cooperado_form"("cooperative_id", "cpf_cooperado");

-- AddForeignKey
ALTER TABLE "ficha_cooperado_form" ADD CONSTRAINT "ficha_cooperado_form_cooperative_id_fkey" FOREIGN KEY ("cooperative_id") REFERENCES "cooperative"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
